### ISSUE TITLE
make header smaller

### ISSUE THREAD

**Issue by JuliaB1** [JuliaB1/acmw-website#2]
Let's change it to make it not take up so much vertical space. It's too large rn lol

**Comment by ogradylena** [comment]
Changing the height and leaving the width fixed at 100% would "squash" the header, do we want to decrease both to keep the proportions of the image constant? The issue is then there's blank space on either side

**Comment by JuliaB1** [comment]
Ooh yeah good point - I think I might've made the header graphic a bit too large but we can table it for now - just checked your fix out and it looks good!
